# Generated by Django 4.0.3 on 2022-03-23 11:15

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_alter_class_tests_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_tests',
            name='sec',
            field=models.TextField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_tests',
            name='time',
            field=models.TimeField(default=datetime.datetime(2022, 3, 23, 11, 15, 1, 597052, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcements',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='class_tests',
            name='type',
            field=models.CharField(blank=True, choices=[('mcq', 'Mcq'), ('written', 'Written'), ('viva', 'Viva')], max_length=10),
        ),
    ]
