# Generated by Django 4.0.3 on 2022-03-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0014_class_tests_sec_class_tests_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='routineTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('saturday', 'Sat'), ('sunday', 'Sun'), ('monday', 'Mon'), ('tuesday', 'Tue'), ('wednesday', 'Wed'), ('thursday', 'Thur'), ('friday', 'Fri')], max_length=10)),
                ('course', models.TextField(max_length=10)),
                ('teacher', models.TextField(max_length=20)),
                ('time', models.TimeField()),
                ('roomNo', models.TextField(blank=True, max_length=100)),
                ('linkToClass', models.URLField(blank=True)),
            ],
        ),
    ]
