# Generated by Django 4.0.3 on 2022-03-23 12:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_routinetasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='teacher',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 12, 20, 5, 443097, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class_tests',
            name='teacher',
            field=models.CharField(default=datetime.datetime(2022, 3, 23, 12, 20, 15, 300204, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
